repos:
  - repo: https://github.com/ambv/black
    rev: "23.11.0"
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.6.1" # Use the sha / tag you want to point at
    hooks:
      - id: mypy
        args: [--explicit-package-bases, --ignore-missing-imports]
